version: '3.9'

services:

  service:
    build: .
    container_name: application
    environment:
      ### Server config ###
      # JVM
      JAVA_OPTS: "-Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
      MEMORY_OPTS: -Xms1g -Xmx1g
      # Postgres
      PG_DB_HOST: db
      PG_DB_PORT: 5432
      PG_DB_SCHEMA: app_schema_flyway
      PG_DB_USERNAME: app_user
      PG_DB_PASSWORD: app_password
    ports:
      - "8080:8080"
      - "5005:5005" # java debug port
    depends_on:
      - db

  db:
    image: postgres
    container_name: db
    restart: on-failure
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
      POSTGRES_DB: app_schema_flyway
    ports:
      - "5432:5432"